services:
  - type: web
    name: kabelux
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node .output/server/index.mjs
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: false
